### ISSUE TITLE
How to write on Windows ?

### ISSUE THREAD

**Issue by Maxmudjon** [HomeACcessoryKid/ESP8266-HomeKit-Demo#1]
how to write on Windows 10

**Comment by AdySan** [comment]
Doesn't esptool.py work on Windows 10?

**Comment by Maxmudjon** [comment]
only linux

**Comment by AdySan** [comment]
Nope, read this https://learn.adafruit.com/building-and-running-micropython-on-the-esp8266/flash-firmware

**Comment by Maxmudjon** [comment]
Instructions for ESP8266-HomeKit will youtube
