### ISSUE TITLE
How do I add an MAC address to the device name?

### ISSUE THREAD

**Issue by kostasoft** [HomeACcessoryKid/ESP8266-HomeKit-Demo#21]
Hello! Sorry for the stupid question.

File: user_main.c
Void: hkc_user_init

chas=addService(      sers,++iid,APPLE,SWITCH_S);
addCharacteristic(chas,aid,++iid,APPLE,NAME_C,"Switch",NULL);

How to add the MAC address so that it was "Switch_01020304"

**Comment by HomeACcessoryKid** [comment]
use a variation on this:
`
>     char mac[6];
>     wifi_get_macaddr(STATION_IF, mac);
>     sprintf(myUsername,"%02X:%02X:%02X:%02X:%02X:%02X",mac[0],mac[1],mac[2],mac[3],mac[4],mac[5]);
`

**Comment by HomeACcessoryKid** [comment]
If you are happy about this answer, then please close the issue?

**Comment by kostasoft** [comment]
Sorry, thank you!
