### ISSUE TITLE
ls: cannot access '../../bin/eagle.[if]*': No such file or directory

### ISSUE THREAD

**Issue by supersjimmie** [HomeACcessoryKid/ESP8266-HomeKit-Demo#26]
I get:
```
Generate eagle.flash.bin and eagle.irom0text.bin successully in BIN_PATH
eagle.flash.bin-------->0x00000
eagle.irom0text.bin---->0x20000
!!!
Thu Sep 21 10:13:48 DST 2017
ls: cannot access '../../bin/eagle.[if]*': No such file or directory
../../../esptool/esptool.py --baud 230400 -p /dev/cu.usbserial-AH02MF3H write_flash 0x00000 ../../bin/eagle.flash.bin 0x14000 ../../bin/eagle.irom0text.bin
```

Is that ```ls: cannot access '../../bin/eagle.[if]*': No such file or directory``` cosmetic or an issue?

**Comment by supersjimmie** [comment]
I guess it had to be ```ls -l $BIN_PATH/eagle.[if]*```?
And then for the next line, also with the $BIN_PATH:
```
echo ../../../esptool/esptool.py --baud 230400 -p /dev/cu.usbserial-AH02MF3H write_flash 0x00000 $BIN_PATH/eagle.flash.bin 0x14000 $BIN_PATH/eagle.irom0text.bin
```

**Comment by HomeACcessoryKid** [comment]
I propose you reinstall your development environment from scratch.

It works for everyone except you.

Pay good attention to all the details of the installation instructions.

Good luck,
HacK

**Comment by supersjimmie** [comment]
It all seems to work now (other issues are solved)
It's only the last 'ls' that seems incorrect.
That ls fails because it ignores the $BIN_PATH variable and goes straight to the hard fixed ../../bin. That works if you have the BIN_PATH in that location, but mine is somewhere else.  Thats what using the BIN_PATH fixes, insted oth the hardcoded ../../bin.
