### ISSUE TITLE
{Enhancement} Suggestions

### ISSUE THREAD

**Issue by felixekman** [HomeACcessoryKid/ESP8266-HomeKit-Demo#3]
- [x] Add button switch to example, that reflects in Home app. I.e. a physical button on the ESP8266 switches the light on/off and status is reflected in the Home app. #4 #6

- [ ] Add more profiles/examples? Doorbell, Switch, Lightbulb, Fan, Garage Door, Window Blinds?, Motion Sensor (with push notification)

**Comment by AdySan** [comment]
Agree on both suggestions, a physical button is perhaps more intuitive/useful example than a 15 second timer. Feel free to add more service examples and make pull requests.

**Comment by HomeACcessoryKid** [comment]
I would like to keep the initial Demo as simple as possible.
We need to find a way to create parallel examples that can be tried after the initial one.
Considering each of them could need a specific driver etc... how would we do this?
Create more repositories??
An example directory?

What do you say?

**Comment by AdySan** [comment]
I vote for example directory. Just like HAP-NodeJS, it'll be nice to have a set of accessories to start with.

**Comment by HomeACcessoryKid** [comment]
Reordered the structure: now there is nothing at the top level and every example code is in its own sub-directory - this will scale fantastic. The Demo is only one of the 'modules'.
Hope you like it...

**Comment by HomeACcessoryKid** [comment]
Just added button-led as a new example module

**Comment by felixekman** [comment]
Great, just tested it out and it looks great. I was planing on building on your code to make a MQTT/Alexa/Homekit combo for the new cheap switches popping up. But sadly it's beyond my skill to rebuild your code into NOOS so that it can be an Arduino library. But if you or someone is able to do it I'll take it from there and pull it all together with OTA and some other goodies if people are interested.
