### ISSUE TITLE
Pairing failing on AiLight

### ISSUE THREAD

**Issue by Maxmudjon** [HomeACcessoryKid/ESP8266-HomeKit-Demo#32]
ets Jan  8 2013,rst cause:2, boot mode:(3,7)

load 0x40100000, len 32048, room 16 
tail 0
chksum 0xda
load 0x3ffe8000, len 2996, room 8 
tail 12
chksum 0xdd
ho 0 tail 12 room 4
load 0x3ffe8bc0, len 3640, room 12 
tail 12
chksum 0xb3
csum 0xb3
OS SDK ver: 1.5.0-dev(4e7f435) compiled @ Aug 25 2017 19:26:38
phy ver: 1055_1, pp ver: 10.7

rf cal sector: 11
w_flash
tcpip_task_hdl : 3fff0d28, prio:10,stack:512
idle_task_hdl : 3fff0dc8,prio:0, stack:384
tim_task_hdl : 3fff3580, prio:2,stack:512
start of user_init @ 301
hkc by HomeACcessoryKid! Compiled Oct 25 2017@03:32:47 Heap: 47424
EspMsgMutex created
ffffffffffffffffffffffffffffffff00
initializing flash in 5 seconds
initializing flash
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
key written: 0
1477a63bae5d22d7e643adc2437722ad4b921cbea9903f92d673f70b597d4b9b42475deaa85d94a86efcbd648243e3a953286c8358f3d3688e6ca7b53f57aaa5
username written: F5:80:EFE30:72:1
myUsername: F5:80:EF:30:72:1E
pairing: 1
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
end of user_init @ 5523
mode : sta(5c:cf:7f:10:45:ef)
add if0
system time: 5534
s: d4cc6637d0e7913a3332df3759c584e0
b: e226aca19d76446580575f112e2ab5525eb5cd4460966d469e385fdf8d7d00a3
scandone
state: 0 -> 2 (b0)
state: 2 -> 3 (0)
state: 3 -> 5 (10)
add 0
aid 7
pm open phy_2,type:2 0 0
cnt 

connected with Payziyev Residence, channel 6
dhcp client start...
ip:192.168.1.9,mask:255.255.255.0,gw:192.168.1.1
srp_prepare done: system time: 30114
B: 4623adb259df5c41451e1c690d6746da3ba6f7c86807b9d4302d3793dad46255b1ba4c3378b6a84b6b276ae314c51711c96bd77d03da26ec17d2b0e3bbe18a900c19e4ac1538cb67ee51e0dc3e69cde46b3546fae0c773569a2b2de1349b7affb1beb38eb2a1edf552e7030f97911873b9a3fcfc9d5146d41426aed6abd08130849806b18ece89333eea023fdaf4301a22c7e08f34505333318186c3a430242e5b0c09638bb1a7b23195e2eaabf7c335c81bfd5505929aee2eb54ea92b8c0da45f8dd2a66cf2e80cd1b22e5dc7d5b2e12a5a805ce6f54fd1a8e131e92eaab699f771bc0c7918d0e3ae3023fd985d1c1b6a1b67223060eb9dc9f2909b8e37456947614bc4ea7a3e9b96b1736566227068624c92cc569ba23a4545aa2b7e38a82d576331944361b2eff11d3569060d8e1ad3ab92b32907245b885d1d9400ddee702f4b3add473dc9684198caf32cda6a8ef1c76b375d60c5e63f1420071b685c845619947facef8e9816b13796831efde8a724683ae165592625693071d6d959cf
ServerInitPriority:1
pairing 1, heap 31968, system time=30243
waiting for task
pairing 1, heap 31968, system time=33242
pairing 1, heap 31968, system time=36242
pairing 1, heap 31968, system time=39242
pairing 1, heap 31968, system time=42242
pairing 1, heap 31968, system time=45242
pairing 1, heap 31968, system time=48242
pairing 1, heap 31968, system time=51242
pairing 1, heap 31968, system time=54242
pairing 1, heap 31968, system time=57242
pairing 1, heap 31968, system time=60242
pairing 1, heap 31968, system time=63244
pairing 1, heap 31968, system time=66242
pairing 1, heap 31968, system time=69242
pairing 1, heap 31968, system time=72242
pairing 1, heap 31968, system time=75242
pairing 1, heap 31968, system time=78242
pairing 1, heap 31968, system time=81242
pairing 1, heap 31968, system time=84242
pairing 1, heap 31968, system time=87242
pairing 1, heap 31968, system time=90242
pairing 1, heap 31968, system time=93242
pairing 1, heap 31968, system time=96242
pairing 1, heap 31968, system time=99242
pairing 1, heap 31968, system time=102242
pairing 1, heap 31968, system time=105242
pairing 1, heap 31968, system time=108242
pairing 1, heap 31968, system time=111242
pairing 1, heap 31968, system time=114242
pairing 1, heap 31968, system time=117242
pairing 1, heap 31968, system time=120242
pairing 1, heap 31968, system time=123242
pairing 1, heap 31968, system time=126242
pairing 1, heap 31968, system time=129242
pairing 1, heap 31968, system time=132242
pairing 1, heap 31968, system time=135242
pairing 1, heap 31968, system time=138242
pairing 1, heap 31968, system time=141242
pairing 1, heap 31968, system time=144243
pairing 1, heap 31968, system time=147242
pairing 1, heap 31968, system time=150242
pairing 1, heap 31968, system time=153242
pairing 1, heap 31968, system time=156242
pairing 1, heap 31968, system time=159242
pairing 1, heap 31968, system time=162242
pairing 1, heap 31968, system time=165242
pairing 1, heap 31968, system time=168242
pairing 1, heap 31968, system time=171242
pairing 1, heap 31968, system time=174242
pairing 1, heap 31968, system time=177242
pairing 1, heap 31968, system time=180242
pairing 1, heap 31968, system time=183242
pairing 1, heap 31968, system time=186242
pairing 1, heap 31968, system time=189242
pairing 1, heap 31968, system time=192242
pairing 1, heap 31968, system time=195242
pairing 1, heap 31968, system time=198242
pairing 1, heap 31968, system time=201242
pairing 1, heap 31968, system time=204242
pairing 1, heap 31968, system time=207242
pairing 1, heap 31968, system time=210242
pairing 1, heap 31968, system time=213242
pairing 1, heap 31968, system time=216242
pairing 1, heap 31968, system time=219242
pairing 1, heap 31968, system time=222242
pairing 1, heap 31968, system time=225242
pairing 1, heap 31968, system time=228242
pairing 1, heap 31968, system time=231242
pairing 1, heap 31968, system time=234242
pairing 1, heap 31968, system time=237242
pairing 1, heap 31968, system time=240242
pairing 1, heap 31968, system time=243242
pairing 1, heap 31968, system time=246242
p_sema taken
3fff26d0  connects  from 192.168.1.4:57584 id:00000001
p_sema locked
server got a packet from 192.168.1.4:57584 at 248415
len:126
len:126
A_dat:6,tot:6,lenght:6
dsl: 6, tl: 6, hl: 120, len: 6
normal packet saved
POST/S: pair-setup C:  F: 
pParseB: 000100060101
pair-setup
t:0-n:1
t:6-n:1
0:00
6:01
Free heap1:30600
srp pair step 1! Free heap:30160
s: d4cc6637d0e7913a3332df3759c584e0
i=0,t=6,l=1
i=8,t=2,l=16
i=32,t=3,l=384
chunked_len: 432
Priority:10
485454502f312e3120323030204f4b0d0a436f6e74656e742d747970653a206170706c69636174696f6e2f70616972696e672b746c76380d0a436f6e6e656374696f6e3a206b6565702d616c6976650d0a5472616e736665722d456e636f64696e673a206368756e6b65640d0a0d0a330d0a0601020d0a31320d0a0210d4cc6637d0e7913a3332df3759c584e00d0a3138340d0a03ff4623adb259df5c41451e1c690d6746da3ba6f7c86807b9d4302d3793dad46255b1ba4c3378b6a84b6b276ae314c51711c96bd77d03da26ec17d2b0e3bbe18a900c19e4ac1538cb67ee51e0dc3e69cde46b3546fae0c773569a2b2de1349b7affb1beb38eb2a1edf552e7030f97911873b9a3fcfc9d5146d41426aed6abd08130849806b18ece89333eea023fdaf4301a22c7e08f34505333318186c3a430242e5b0c09638bb1a7b23195e2eaabf7c335c81bfd5505929aee2eb54ea92b8c0da45f8dd2a66cf2e80cd1b22e5dc7d5b2e12a5a805ce6f54fd1a8e131e92eaab699f771bc0c7918d0e3ae3023fd985d1c1b6a1b67223060eb9dc9f2909b8e374503816947614bc4ea7a3e9b96b1736566227068624c92cc569ba23a4545aa2b7e38a82d576331944361b2eff11d3569060d8e1ad3ab92b32907245b885d1d9400ddee702f4b3add473dc9684198caf32cda6a8ef1c76b375d60c5e63f1420071b685c845619947facef8e9816b13796831efde8a724683ae165592625693071d6d959cf0d0a300d0a0d0a
to be sent by tlv8_send routine
arg=3fff2940, ptrespconn=3fff26d0, pcryp=3fff2940
send result: 0
Free heap2:28960
server sent a packet to  192.168.1.4:57584 at 249122
pairing 1, heap 30752, system time=249242
p_sema locked
server got a packet from 192.168.1.4:57584 at 251474
len:579
len:579
A_dat:457,tot:457,lenght:457
dsl: 457, tl: 457, hl: 122, len: 457
normal packet saved
POST/S: pair-setup C:  F: 
pParseB: 06010303ff8e809402eaf4ae809fef89c4317247d94171f596aeb5b16c8ac1c47ca89f3788dee70348c5df48d7073da64d8436a52d840f173c4941f6e61c87a6474d06878aaf4d52839a96a7ed233815b9404637c2d949a59c66868d4de8416f2c9632db05bb7a40107e49f0ae8e43031e3685f50f0b02186be30e9c66f19e440dcc9e8e4e2ea0ed4fed12f024244e254b4c804631e8a2cf2b9c061ee3a3ce414a0b92ff8bd3bcf539ebeacfd80a0566534f87a001dccd058c446cd07179bfcecd282c444ea4fd66bf1f60196860b4969332681210ba69eab117c8b3341a5085af374c7806320ffc524b13ac5d7e25c7b59e4bd4545cf68c792120b22297d1a6226354c00381c104687da7c7f8a782c0dfd82ae33b8e9a6c8435070fad69439757fc459d9ab186c7706bd5dd2988af1e49a6816f3c5119c5b286c15adb65d77f5449057dbac68094d45fc269965c349f6ceaf7d93bcec7016da7e23f94b497680f751df428c754976fd32e9258d224bfb71a74d5e44f45f4c4d6410606353e339f778aca2ff58c0440b51fa8f1fbad42fd48abffcfde6cbca6ebfdab11736071a06d7b39cae98fa1669a3d44407596b0d6e2d3e6c67650bf017a1b2b84b5c3ad4fb8e0e90a5e1202bf
pair-setup
t:6-n:1
t:3-n:255
t:3-n:384
t:4-n:64
3:8e809402eaf4ae809fef89c4317247d94171f596aeb5b16c8ac1c47ca89f3788dee70348c5df48d7073da64d8436a52d840f173c4941f6e61c87a6474d06878aaf4d52839a96a7ed233815b9404637c2d949a59c66868d4de8416f2c9632db05bb7a40107e49f0ae8e43031e3685f50f0b02186be30e9c66f19e440dcc9e8e4e2ea0ed4fed12f024244e254b4c804631e8a2cf2b9c061ee3a3ce414a0b92ff8bd3bcf539ebeacfd80a0566534f87a001dccd058c446cd07179bfcecd282c444ea4fd66bf1f60196860b4969332681210ba69eab117c8b3341a5085af374c7806320ffc524b13ac5d7e25c7b59e4bd4545cf68c792120b22297d1a6226354c0c104687da7c7f8a782c0dfd82ae33b8e9a6c8435070fad69439757fc459d9ab186c7706bd5dd2988af1e49a6816f3c5119c5b286c15adb65d77f5449057dbac68094d45fc269965c349f6ceaf7d93bcec7016da7e23f94b497680f751df428c754976fd32e9258d224bfb71a74d5e44f45f4c4d6410606353e339f778aca2ff58c
4:b51fa8f1fbad42fd48abffcfde6cbca6ebfdab11736071a06d7b39cae98fa1669a3d44407596b0d6e2d3e6c67650bf017a1b2b84b5c3ad4fb8e0e90a5e1202bf
6:03
Free heap3:29696
Free heap4:29696
srp pair step 3!

Free heap:31024
pairing 1, heap 25024, system time=252242
pairing 1, heap 11288, system time=255252
3fff26d0 conn, rev:3fff0930, nxt:00000000, act:3, 192.168.1.4:57584, cid:01
pairing 1, heap 9240, system time=258262
pairing 1, heap 11288, system time=261272
pairing 1, heap 11288, system time=264282
pairing 1, heap 9240, system time=267292
3fff26d0 conn, rev:3fff0930, nxt:00000000, act:3, 192.168.1.4:57584, cid:01
pairing 1, heap 7048, system time=270302
pairing 1, heap 9096, system time=273312
pairing 1, heap 7048, system time=276322
key: 14a1a13864ad550c0281738accdeb00d38c0f15705f3c549a78dec37883c552999a73e38b8b89c679ec5b0ae7507400627e1906e09ded90a738894fe510b7a34
i=0,t=6,l=1
i=8,t=4,l=64
chunked_len: 85
485454502f312e3120323030204f4b0d0a436f6e74656e742d747970653a206170706c69636174696f6e2f70616972696e672b746c76380d0a436f6e6e656374696f6e3a206b6565702d616c6976650d0a5472616e736665722d456e636f64696e673a206368756e6b65640d0a0d0a330d0a0601040d0a34320d0a04402768385d1b6a3db8563ce7c840da5f98bdaef8e03ec69110aea9b4696f748e5655747b242a21f0a7b14f2470bb8a54afca4662424f4659c624bc7176ca29dec50d0a300d0a0d0a
to be sent by tlv8_send routine
arg=3fff2940, ptrespconn=3fff26d0, pcryp=3fff2940
send result: 0
waiting for task
server sent a packet to  192.168.1.4:57584 at 277380
p_sema locked
server got a packet from 192.168.1.4:57584 at 277404
len:281
len:281
A_dat:159,tot:159,lenght:159
dsl: 159, tl: 159, hl: 122, len: 159
normal packet saved
POST/S: pair-setup C:  F: 
pParseB: 059a82e2a5ba325236dcc963685f0733d8c484b0aaf51cc65a7145a4bbd2b7c812470a93e3fa6505224ade8b226463d0984d028d3a0487ed50d879c251df5f024199da4d8f91a4ecec9af76a6cb8c1f3deb76b0521ee576eae92b9481b939ebfa3431b1eaeae8c775e25618844e9bd8e23d092b17f9a72957ce1722afd3f95b7063455022a43f6495bd05d731ddcc06fb6ebe490df6a43864dfe1c8f060105
pair-setup
t:5-n:154
t:6-n:1
5:82e2a5ba325236dcc963685f0733d8c484b0aaf51cc65a7145a4bbd2b7c812470a93e3fa6505224ade8b226463d0984d028d3a0487ed50d879c251df5f024199da4d8f91a4ecec9af76a6cb8c1f3deb76b0521ee576eae92b9481b939ebfa3431b1eaeae8c775e25618844e9bd8e23d092b17f9a72957ce1722afd3f95b7063455022a43f6495bd05d731ddcc06fb6ebe490df6a43864dfe1c8f
6:05
Free heap5:30200
Free heap6:30200
srp pair step 5!

Free heap:30840
encKey0:ecb89bcac5233a648d84ee8beb4ea5ad89f1d40a67a7cdbbada4f98f34b70517
t:1-n:36
t:3-n:32
t:10-n:64
1:32313634353037462d343445432d344636372d423138432d413934333135314543423938
3:a7e3235f8ac208d0b499e52d3f2a27986215f135b28f498eb84d957304e8a45d
10:f3fffbb426cb704879f43208bfd2ae06f0df9e41ec5217c18bb2bc0a4e96e6d3f9eda74efcbbd7cc24e08375d923543f162a62ee0b9d07449ca2c7624c1e9709
myLTPK: 42475deaa85d94a86efcbd648243e3a953286c8358f3d3688e6ca7b53f57aaa5
verified=1 r=0
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
writing paired client to flash
7fffffffffffffffffffffff32313634353037462d343445432d344636372d423138432d413934333135314543423938a7e3235f8ac208d0b499e52d3f2a27986215f135b28f498eb84d957304e8a45d
i=0,t=6,l=1
i=8,t=5,l=135
chunked_len: 156
identify_task started
bri 100
h=0,s=0,b=100
r=0,g=0,b=0,w=4095
{
	"accessories":	[{
			"aid":	1,
			"services":	[{
					"iid":	1,
					"type":	"0000003E-0000-1000-8000-0026BB765291",
					"characteristics":	[{
							"iid":	2,
							"type":	"00000023-0000-1000-8000-0026BB765291",
							"perms":	["pr"],
							"format":	"string",
							"maxLen":	64,
							"value":	"AiLightS"
						}, {
							"iid":	3,
							"type":	"00000020-0000-1000-8000-0026BB765291",
							"perms":	["pr"],
							"format":	"string",
							"maxLen":	64,
							"value":	"HacK"
						}, {
							"iid":	4,
							"type":	"00000021-0000-1000-8000-0026BB765291",
							"perms":	["pr"],
							"format":	"string",
							"maxLen":	64,
							"value":	"Rev-1"
						}, {
							"iid":	5,
							"type":	"00000030-0000-1000-8000-0026BB765291",
							"perms":	["pr"],
							"format":	"string",
							"maxLen":	64,
							"value":	"10000"
						}, {
							"iid":	6,
							"type":	"00000014-0000-1000-8000-0026BB765291",
							"perms":	["pw"],
							"format":	"bool"
						}]
				}, {
					"iid":	7,
					"type":	"00000043-0000-1000-8000-0026BB765291",
					"characteristics":	[{
							"iid":	8,
							"type":	"00000023-0000-1000-8000-0026BB765291",
							"perms":	["pr"],
							"format":	"string",
							"maxLen":	64,
							"value":	"light"
						}, {
							"iid":	9,
							"type":	"00000025-0000-1000-8000-0026BB765291",
							"perms":	["pw", "pr", "ev"],
							"format":	"bool",
							"events":	true,
							"value":	true
						}, {
							"iid":	10,
							"type":	"00000013-0000-1000-8000-0026BB765291",
							"perms":	["pw", "pr", "ev"],
							"minValue":	0,
							"maxValue":	360,
							"minStep":	1,
							"unit":	"arcdegrees",
							"format":	"float",
							"events":	true,
							"value":	0
						}, {
							"iid":	11,
							"type":	"0000002F-0000-1000-8000-0026BB765291",
							"perms":	["pw", "pr", "ev"],
							"minValue":	0,
							"maxValue":	100,
							"minStep":	1,
							"unit":	"percentage",
							"format":	"float",
							"events":	true,
							"value":	0
						}, {
							"iid":	12,
							"type":	"00000008-0000-1000-8000-0026BB765291",
							"perms":	["pw", "pr", "ev"],
							"minValue":	0,
							"maxValue":	100,
							"minStep":	1,
							"unit":	"percentage",
							"format":	"int",
							"events":	true,
							"value":	100
						}]
				}]
		}]
}
485454502f312e3120323030204f4b0d0a436f6e74656e742d747970653a206170706c69636174696f6e2f70616972696e672b746c76380d0a436f6e6e656374696f6e3a206b6565702d616c6976650d0a5472616e736665722d456e636f64696e673a206368756e6b65640d0a0d0a330d0a0601060d0a38390d0a058719fcbbc86f5a3b718ed4acdeb9768c421f5860e5948ee0e8a8ca0d0fb4c4dd3d1bea8682d5121f89a4db0d6f6c0a7631e3251ade15129bf2c8d2894ed8115ce8180d587d7c8643ba33f73ab9fb79dd1653c0aae4389c8f783c75064506f0e99c48d8431cbda6dce14bb8e10fe516ded36c1441d71ab7d6546ed2471e6d0574016687a5f9386f610d0a300d0a0d0a
to be sent by tlv8_send routine
arg=3fff2940, ptrespconn=3fff26d0, pcryp=3fff2940
send result: 0
waiting for task
server sent a packet to  192.168.1.4:57584 at 278627
client 192.168.1.4:57584 disconnected with status 0
Cleaning 3fff2940 @ 279265 CID: 1
Freeing  3fff2940 @ 279266
p_sema taken
3fff27e8  connects  from 192.168.1.4:57585 id:00000001
p_sema locked
server got a packet from 192.168.1.4:57585 at 279287
len:159
len:159
A_dat:37,tot:37,lenght:37
dsl: 37, tl: 37, hl: 122, len: 37
normal packet saved
POST/S: pair-verify C:  F: 
pParseB: 0601010320bc21736e836bf2188db3b408ae07c68901069fd0740b1e58984de0b07db0847a
pair-verify
t:6-n:1
t:3-n:32
3:bc21736e836bf2188db3b408ae07c68901069fd0740b1e58984de0b07db0847a
6:01
Free heap1:21352
Free heap2:21352
pairing 1, heap 21560, system time=279335
pair verify step 1 at 279340

Free heap:21928
mycurvekey: b6abd7374f42e248078c4efaa852791136c909f794b201fe8c3baf8b65532f50
clcurvekey: bc21736e836bf2188db3b408ae07c68901069fd0740b1e58984de0b07db0847a
system time: 279605
shared secret time: 261
sessionkey: cbb3919787af93cc2f172f23f633126e7687333d90c196f2a3abb045a16d5654
system time: 279867
sign message time: 100
edsign: 0
system time: 279967
i=0,t=6,l=1
i=8,t=5,l=101
i=117,t=3,l=32
chunked_len: 162
485454502f312e3120323030204f4b0d0a436f6e74656e742d747970653a206170706c69636174696f6e2f70616972696e672b746c76380d0a436f6e6e656374696f6e3a206b6565702d616c6976650d0a5472616e736665722d456e636f64696e673a206368756e6b65640d0a0d0a330d0a0601020d0a36370d0a05654302e7ee593a955caf4efd972cbc976488997692bfb6f01c92137ba1305460e2a5868f0b4f3ef4cb749dd004b7c5f0d257fae354627bccf2f9feebf8f7ec62df6b55c9faf585a3579d6e8154336138ef78099b16016dff0b767ba2bf84c4e3adbf76d5007d0d0a32320d0a0320b6abd7374f42e248078c4efaa852791136c909f794b201fe8c3baf8b65532f500d0a300d0a0d0a
to be sent by tlv8_send routine
arg=3fff2a20, ptrespconn=3fff27e8, pcryp=3fff2a20
send result: 0
waiting for task
server sent a packet to  192.168.1.4:57585 at 280138
p_sema locked
server got a packet from 192.168.1.4:57585 at 280185
len:248
len:248
A_dat:125,tot:125,lenght:125
dsl: 125, tl: 125, hl: 123, len: 125
normal packet saved
POST/S: pair-verify C:  F: 
pParseB: 0578fd3d311765c19b7a8c7a7f9d022ad37f89afc4a28b169144770dbfae61b1f57c706d58b07ccf365a396e9017aba3a196f60614ffad9f2e0764593362b3ca7c6364b725469c57ad18b485f640f722a68be0f233d92a76e67d47424b2002f795ef1b0ff21d0b1e1fbeeebee4d61c968670c7c77e3cd7706a33060103
pair-verify
t:5-n:120
t:6-n:1
5:fd3d311765c19b7a8c7a7f9d022ad37f89afc4a28b169144770dbfae61b1f57c706d58b07ccf365a396e9017aba3a196f60614ffad9f2e0764593362b3ca7c6364b725469c57ad18b485f640f722a68be0f233d92a76e67d47424b2002f795ef1b0ff21d0b1e1fbeeebee4d61c968670c7c77e3cd7706a33
6:03
Free heap3:21160
Free heap4:21160
pair verify step 3 at 280273

Free heap:21928
t:1-n:36
t:10-n:64
1:32313634353037462d343445432d344636372d423138432d413934333135314543423938
10:d7dcf3b6a91a073c2cea12f411d1074fed4be0e63a9b11f0ad45b8c6f94e24f376de42f149bb18995e49a8baf588b9db724f5883fa2477db998940f5b7551204
2164507F-44EC-4F67-B18C-A943151ECB98 -- 7fffffffffffffffffffffff32313634353037462d343445432d344636372d423138432d413934333135314543423938a7e3235f8ac208d0b499e52d3f2a27986215f135b28f498eb84d957304e8a45d
key 0 loaded - result: 0
system time: 280341
system time: 280343
verify message time: 312, verified=1 r=0
i=0,t=6,l=1
chunked_len: 13
485454502f312e3120323030204f4b0d0a436f6e74656e742d747970653a206170706c69636174696f6e2f70616972696e672b746c76380d0a436f6e6e656374696f6e3a206b6565702d616c6976650d0a5472616e736665722d456e636f64696e673a206368756e6b65640d0a0d0a330d0a0601040d0a300d0a0d0a
to be sent by tlv8_send routine
arg=3fff2a20, ptrespconn=3fff27e8, pcryp=3fff2a20
send result: 0
server sent a packet to  192.168.1.4:57585 at 280705
waiting for task
3fff27e8 conn, rev:3fff0930, nxt:00000000, act:3, 192.168.1.4:57585, cid:01
pairing 1, heap 21560, system time=282342
pairing 1, heap 21560, system time=285342
pairing 1, heap 21560, system time=288342
pairing 1, heap 21560, system time=291342
3fff27e8 conn, rev:3fff0930, nxt:00000000, act:3, 192.168.1.4:57585, cid:01
pairing 1, heap 21560, system time=294342
pairing 1, heap 21560, system time=297342
pairing 1, heap 21560, system time=300342
pairing 1, heap 21560, system time=303342
3fff27e8 conn, rev:3fff0930, nxt:00000000, act:3, 192.168.1.4:57585, cid:01
pairing 1, heap 21560, system time=306343
pairing 1, heap 21560, system time=309342
pairing 1, heap 21560, system time=312342
pairing 1, heap 21560, system time=315342
3fff27e8 conn, rev:3fff0930, nxt:00000000, act:3, 192.168.1.4:57585, cid:01
pairing 1, heap 21560, system time=318342
pairing 1, heap 21560, system time=321342
pairing 1, heap 21560, system time=324342
pairing 1, heap 21560, system time=327342
3fff27e8 conn, rev:3fff0930, nxt:00000000, act:3, 192.168.1.4:57585, cid:01
pairing 1, heap 21560, system time=330342
pairing 1, heap 21560, system time=333342
pairing 1, heap 21560, system time=336342
pairing 1, heap 21560, system time=339342
client 192.168.1.4:57585 disconnected with status 0
Cleaning 3fff2a20 @ 340864 CID: 1
Freeing  3fff2a20 @ 340865
pairing 1, heap 22768, system time=342342

**Comment by HomeACcessoryKid** [comment]
this is a _normal_ failing pair attempt, just keep trying. Yesterday it took me 20 attempts to get it done.
I think it has to do with bad wifi but cannot proof it.
