### ISSUE TITLE
how to flash help

### ISSUE THREAD

**Issue by Kristian8606** [HomeACcessoryKid/ESP8266-HomeKit-Demo#43]
echo ../../../esptool/esptool.py --baud 230400 -p /dev/cu.usbserial-* write_flash 0x00000 $BIN_PATH/eagle.flash.bin 0x14000 $BIN_PATH/eagle.irom0text.bin No such file or directory

**Comment by supersjimmie** [comment]
See https://github.com/HomeACcessoryKid/ESP8266-HomeKit-Demo/issues/26

**Comment by Kristian8606** [comment]
Thanks
